posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(),name='create'),
    re_path(r'^by/(?P<username>[-\w]+)/', views.UserPosts.as_view(),name='for_user'),
    re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete')
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts', null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = self.message
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic
from django.contrib import messages


from braces.views import SelectRelatedMixin
# Create your views here.
from . import models
from . import forms


from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):

    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args, **kwargs):
        messages.success(self.request, 'Post Delete')
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<div class="post media">
  <h3>{{post.message_html|safe}}</h3>
  <div class="media-body">
    <h5 class="media-heading">
    <span class="username">
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
    </span>

    <time class="time">
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
        {{post.created_at}}
      </a>
    </time>
    </h5>

    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
          <span class="glyphicon glyphicon-remove text-danger" aria-hiden='true'></span>
          <span class="text-danger icon-label">Delete</span>
        </a>
      {% endif %}

    </div>

  </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="posts-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock  %}
        {% block post_content %}{% endblock  %}
        {% block post_post %}{% endblock  %}
      </div>
    </div>
  </div>
{% endblock  %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>

  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>

  <form method="post">
    {% csrf_token %}
    <input type="submit" name="" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
  </form>

{% endblock  %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% include "posts/_post.html" %}
  </div>
{% endblock  %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
  <h4>Create a new Post</h4>
  <form id="pótForm" action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Post" class="btn btn-primary btn-large">
  </form>
{% endblock  %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your Groups</h5>
          <ul class="list-unstyled">
            {% for member_group in get_user_groups %}
              <li class="group li-with-group">
                <a href="{% url 'groups:single' slug=member_group.group.slug %}">55555555</a>
              </li>
            {% endfor %}

          </ul>
        </div>
      </div>
    {% endif %}

    <div class="card card-with-shadow">
      <div class="content">
        <h5 class="title">All Groups</h5>
        <ul class="list-unstyled">
          {% for other_group in get_other_groups %}
            <li class="group li-with-bullet">
              <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
            </li>
          {% endfor %}

        </ul>
      </div>
    </div>

  </div>
{% endblock  %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}

  </div>
{% endblock  %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
  <div class="col-md-4">
    <h1>@{{post_user.username}}</h1>
  </div>
{% endblock  %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}

  </div>
{% endblock  %}